### ISSUE TITLE
Funds get taken but aren't given to the recipient when Multi-Signer is used with Braavos wallet 

### ISSUE THREAD

**Issue by tuku0x** [Orbiter-Finance/OrbiterModule#21]
Steps to reproduce:

- Use a Multi-Signer enabled Braavos wallet
- Initiate ETH transfer from L2 to L1 on orbiter.finance website
- Second Sign via mobile Braavos app

As a result the funds will be taken from Braavos Wallet but won't be given to L1 side.

**Comment by tuku0x** [comment]
hi, this issue still persists. here's the latest transactions which caused to evaporate my money again.

1. The first transaction was initiated by Orbiter website. 

From StarkNet, to Ethereum, amount was 0.01 ETH.
Sender account: 0x04ce3b538d340c9cd6d54dd340a10a9ec55aca62d92d4b72ecf290651f491333
Receiver account: 0x244815dBd87BB29B15Cc328c957B7DEAf1215eBF

this is the transaction of this first sign: https://starkscan.co/tx/0x6ca2858d9dd40936efc4117489bb8e688f4eb6619a5c123f1538d70510ddf83

2. the second sign is from a mobile phone and here is the transaction: https://starkscan.co/tx/0x03b257c8636ded6908f7ea8b84094156447c26bb9261819d478fe7e7507d8cd2

After the second sign, 0.01 ETH was taken from my StarkNet account. **But** it's not given to my receiver account.

Guys, here I lost 0.01 ETH and before I lost 0.1 ETH. Why don't you fix the bug and resolve the issue? 

@kakui-lau please have a look

**Comment by kakui-lau** [comment]
The latest version already supports multi-signature transactions
